

server:
  port: 8883

spring:
  application:
    name: scg-client-with-eureka
  cloud:
    loadbalancer:
      configurations: health-check # Note: required for enabling SDC with Health Checks - remove this line if you want to reproduce issues because not using HealthChecks in LB
      # Note: LoadBalancerCacheProperties.ttl (or spring.cloud.loadbalancer.cache.ttl) is 35 by default - You will need to wait 35secs after an instance turns healthy
      interval: 5s # Don't wait more than 5 seconds to check endpoints
      refetchInstances: true
    gateway:
      httpclient:
        wiretap: true
      routes:
        - uri: lb://hello-service
          predicates:
            - Path=/hello
          filters:
            - StripPrefix=0

eureka:
  client:
    webclient:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: false
  instance:
    preferIpAddress: true
---
########## [For Testing] ##########
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    # Log when http://localhost:8090/actuator/health is checked behind the scenes
    reactor.netty.http.client: DEBUG